# The west manifest file (west.yml) for the Croxel's KIOTE IoT Repository of nRF Connect SDK (NCS).
#
# The per-workspace west configuration file, ncs/.west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = kiote-iot
#
# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  # This west.yml requires west 0.9 or later, because the "submodules"
  # feature used below was introduced then.
  version: "0.10"

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    # nRF Connect SDK GitHub organization.
    - name: ncs
      url-base: https://github.com/nrfconnect

  # If not otherwise specified, the projects below should be obtained
  # from the ncs remote.
  defaults:
    remote: ncs

  # "projects" is a list of git repositories which make up the NCS
  # source code.
  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: v1.7.0
      path: nrf
      import: true

  # West-related configuration for the nrf repository.
  self:
    # This repository should be cloned to ncs/kiote-iot.
    path: kiote-iot
